#!/bin/sh
# A script for setting up routing tables for MPTCP in the N950.

# Copy this script into /etc/network/if-post-down.d/

set -e

env > /etc/network/if_down_env

UPLOADER_IFACE=wlxc83a35d1021c

if [ "$IFACE" != "$UPLOADER_IFACE" -o "$MODE" != stop ]; then
    exit 0
fi

if [ "$METHOD" != dhcp -a "$METHOD" != ppp -a "$METHOD" != static ]; then
    exit 0
fi

ip rule del table $IFACE
ip route flush table $IFACE
